#+TITLE: Fr33macs, my Nix flake Emacs config
#+AUTHOR: fr33zing
#+PROPERTY: header-args :tangle yes
#+OPTIONS: num:nil H:5 toc:2
#+EXPORT_FILE_NAME: index.html

#+ATTR_HTML: :style display:none;
#+BEGIN_EXAMPLE
Read this document in this repository's github.io page or in Emacs for the best experience.
#+END_EXAMPLE

* TODO ASAP

- SUBLIMITY MODE NEEDS TO GO
  Replace with something from here:
  https://stackoverflow.com/questions/24955253/centre-emacs-buffer-within-window

- Balance windows when a new one opens
- Create a script that checks if emacsclient is already open.
  If open, instead focus it https://wayland.app/protocols/kde-plasma-window-management
  https://github.com/uukelele/waydotool
- Make pressing enter on git diff use existing window if buffer open
- Find out why LTEX errors aren't always working with flycheck
- Find a plugin to show me all my TODOs in all projects when I open Emacs
- Disable LTEX in read only

- Check which external libs are actually needed


* Links

- GitHub.io page: https://fr33zing.github.io/fr33macs
- Repository: https://github.com/fr33zing/fr33macs
  - [[https://github.com/fr33zing/fr33macs/blob/main/flake.nix][flake.nix]] - Nix flake
  - [[https://github.com/fr33zing/fr33macs/blob/main/config.org][config.org]] - Emacs configuration
  - [[https://github.com/fr33zing/fr33macs/blob/main/export.scss][export.scss]] - Org-mode HTML export styles

* About

This document is tangled to create my Emacs configuration. *If you
want to try it for yourself, [[*Try it yourself][click here]].*

Mostly intended for use with Wayland on Linux, this configuration uses
the pure-gtk version of Emacs 29. The build process, including
fetching gathering all external dependencies, is handled by the Nix
flake.

** Build steps

1. Fetch and build external dependencies, including any developer
   tools needed for the languages I use, such as: compilers,
   libraries, formatters, linters, language servers.

2. Use ~sass~ to convert ~export.scss~ into CSS. That CSS is then used
   to style this document when exported to HTML.

3. Tangle configuration from ~config.org~.

4. Substitute variables from Nix flake (including the export CSS) into
   tangled configuration.

5. Build Emacs with tangled and substituted configuration.

6. Wrap Emacs binary to give it exclusive access to its external
   dependencies.

** Scripts

Utility scripts are located in [[file:util/][~util/~]] and they're used to cover parts
of the Nix flake build that wouldn't be worth it to implement in Nix.

*** Tangling

This file is not tangled using ~org-babel-table~. Instead, it's
tangled using a bare-bones implementation in [[file:util/tangle.py][~util/tangle.py~]], and
thus no fancy tangle features are supported. The ~header-args~
property at the top of the file is not even parsed, it's only there to
maintain compatibility with other tangle implementations.

*** Substitution

The function ~getnix~ is used to get a variable from the Nix flake,
sort of like ~getenv~ but not exactly. It isn't actually a function
that exists. Instead, [[file:util/substitute.py][~util/substitute.py~]] is used to substitute all
instances of ~(getnix "variableName")~ with the appropriate elisp
literal.

** Formatting
*** Blank lines

Different elements, (i.e. text, blocks, headings, etc.), should be
separated with blank lines except between multiple headings. Omitting
the blank line between multiple headings is necessary for heading
visibility cycling to work as expected.

*** Tags in comments

While reading this document you may see what look to be XML tags,
e.g.:

#+BEGIN_SRC emacs-lisp :tangle no
(defun something-spanning-multiple-src-blocks ()
  (beginning-of-the-defun))
;; <defun>
#+END_SRC

#+BEGIN_SRC emacs-lisp :tangle no
  (middle-of-the-defun)
#+END_SRC

#+BEGIN_SRC emacs-lisp :tangle no
  (end-of-the-defun)) ; <-- closes the defun
;; </defun>
#+END_SRC

These tags are not parsed. They are only used to indicate to the
reader that code in the same scope may be spread across multiple src
blocks.

* Try it yourself
** Warning

Back up your ~.emacs.d~ directory if you already have a configuration
you care about. I don't /think/ that this will affect it, but back it
up anyway just to be safe.

** Instructions

If you don't have Nix installed, [[https://nixos.org/download.html][click here]].

If you have the experimental features [[https://nixos.wiki/wiki/Nix_command][nix-command]] and [[https://nixos.wiki/wiki/Flakes][flakes]] enabled:

#+BEGIN_SRC shell :tangle no
nix run github:fr33zing/fr33macs
#+END_SRC

If you don't have them enabled, but you want to enable them, [[https://nixos.wiki/wiki/Flakes#Enable_flakes][click here]].

#+BEGIN_SRC shell :tangle no
nix --experimental-features 'nix-command flakes' run github:fr33zing/fr33macs
#+END_SRC

** Permanent installation (Non-NixOS)

If you have an existing Emacs installation... say goodbye.

#+BEGIN_SRC shell :tangle no
nix develop github:fr33zing/fr33macs --install
#+END_SRC

Same deal with the ~--experimental-features~ if you don't have flakes enabled.

* Basic setup

Set default frame position and height. Changing the frame size via the
hook is necessary, for some reason. Doing it the typical way doesn't
seem to have an effect if the frame is resized by dragging the title
bar out of the maximized state.

#+BEGIN_SRC emacs-lisp
(let ((frame-options '((fullscreen . maximized))))
  (dolist (option frame-options)
    (add-to-list 'initial-frame-alist option)
    (add-to-list 'default-frame-alist option)))

(add-hook 'after-make-frame-functions (lambda (frame)
  (run-with-timer 1 nil 'set-frame-size frame 90 45)))
#+END_SRC

Disable unwanted UI elements and startup messages.

#+BEGIN_SRC emacs-lisp
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(setq inhibit-startup-message t
      use-dialog-box nil)
#+END_SRC

Enable some things which should probably be default

#+BEGIN_SRC emacs-lisp
(setq require-final-newline t)
(setq frame-inhibit-implied-resize t)
(global-hl-line-mode)

(save-place-mode 1)
(recentf-mode 1)
(setq recentf-max-menu-items 10)
(setq recentf-max-saved-items 10)
#+END_SRC

Enable relative line numbers globally.

#+BEGIN_SRC emacs-lisp
(setq display-line-numbers-type 'relative)
(global-display-line-numbers-mode)
#+END_SRC

Try to always split window vertically.

#+BEGIN_SRC emacs-lisp
(setq split-width-threshold 0)
(setq split-height-threshold nil)
#+END_SRC

Balance windows automatically.

#+BEGIN_SRC emacs-lisp
(setq window-combination-resize t)
#+END_SRC

Remove secondary selection with mouse.

#+BEGIN_SRC emacs-lisp
(global-unset-key (kbd "<M-drag-mouse-1>"))   ; was mouse-set-secondary
(global-unset-key (kbd "<M-down-mouse-1>"))   ; was mouse-drag-secondary
(global-unset-key (kbd "<M-mouse-1>"))        ; was mouse-start-secondary
(global-unset-key (kbd "<M-mouse-2>"))        ; was mouse-yank-secondary
(global-unset-key (kbd "<M-mouse-3>"))        ; was mouse-secondary-save-then-kill
#+END_SRC

** MELPA

#+BEGIN_SRC emacs-lisp
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/") t)
#+END_SRC

* External libraries

** Dash

Dash is a library for dealing with lists.

#+BEGIN_SRC emacs-lisp
(use-package dash :ensure t)
#+END_SRC

** Map

Map provides generic map-manipulation functions that work on alists,
plists, hash-tables, and arrays.

#+BEGIN_SRC emacs-lisp
(use-package map)
#+END_SRC

** Subr-x

Less commonly used functions that complement basic APIs.

#+BEGIN_SRC emacs-lisp
(use-package subr-x)
#+END_SRC

* Theme

#+BEGIN_SRC emacs-lisp
(use-package catppuccin-theme :ensure t)
(load-theme 'catppuccin t)
(setq catppuccin-flavor (getnix "themeVariant"))
(catppuccin-reload)

(set-face-attribute 'font-lock-number-face nil
  :foreground (catppuccin-get-color 'text))

(set-face-attribute 'font-lock-property-name-face nil
  :foreground (catppuccin-get-color 'text))
(set-face-attribute 'font-lock-property-use-face nil
  :foreground (catppuccin-get-color 'text))
(set-face-attribute 'font-lock-function-call-face nil
  :foreground (catppuccin-get-color 'text))
#+END_SRC

Enable window dividers

#+BEGIN_SRC emacs-lisp
(set-face-foreground 'window-divider (catppuccin-get-color 'crust))
(set-face-foreground 'window-divider-first-pixel nil)
(set-face-foreground 'window-divider-last-pixel nil)
(setq window-divider-default-places t
      window-divider-default-right-width 2
      window-divider-default-bottom-width 2)
(window-divider-mode t)
#+END_SRC

** Variable definitions

#+BEGIN_SRC emacs-lisp
(defvar my:cursor-color (catppuccin-get-color 'sapphire)
  "Default cursor color.")

(defvar my:switch-window-cursor-color (catppuccin-get-color 'red)
  "Cursor color when switching windows.")

(defvar my:code-color (catppuccin-get-color 'text)
  "Default color for text that is considered code.")
#+END_SRC

** Customization

*Notice*: Not all theming is done in this section.

#+BEGIN_SRC emacs-lisp
(set-face-attribute 'default t :font (getnix "font"))

(add-to-list 'default-frame-alist `(cursor-color . ,my:cursor-color))
(set-face-attribute 'region nil
                    :background (catppuccin-get-color 'surface2))

(set-face-attribute 'show-paren-match nil
                    :background (catppuccin-get-color 'pink)
                    :foreground "black")
(set-face-attribute 'show-paren-mismatch nil
                    :background (catppuccin-get-color 'yellow)
                    :foreground "black")
#+END_SRC

* Splash screen
** Library

#+BEGIN_SRC emacs-lisp
(defgroup fr33splash nil
  "fr33macs splash screen."
  :group 'applications
  :prefix "fr33splash-")

(defconst fr33splash-buffer-name "*splash*"
  "fr33splash buffer name.")

(defvar fr33splash--last-size nil
  "The last known size of the buffer.")

(defvar fr33splash--content nil
  "Content to render in the buffer.")

(defvar fr33splash-content-fn nil
  "Function used to generate content.")

(defvar fr33splash--allow-overlap-buffer-names
  ;; " *LV*" = pretty-hydra
  (list fr33splash-buffer-name " *LV*" "*Warnings*")
  "Buffers to avoid killing when splash screen is visible.")

(defun fr33splash-regenerate-content ()
  "Regenerate content with fr33splash-content-fn."
  (setq fr33splash--content (funcall fr33splash-content-fn)))

(define-derived-mode fr33splash-mode
  special-mode "fr33splash"
  "fr33macs splash screen."
  (setq major-mode 'fr33splash-mode)
  (setq-local cursor-type nil)
  (setq-local evil-default-cursor (list nil))
  (setq-local global-hl-line-mode nil)
  (font-lock-mode -1)
  (hl-line-mode -1)
  (display-line-numbers-mode -1))

(defun fr33splash--apply-fixes ()
  "Fix issues caused by other packages."
  (when (boundp 'sublimity-mode)
    (sublimity-mode -1)))

(defun fr33splash--remove-fixes ()
  "Removes fixes for issues caused by other packages."
  (when (boundp 'sublimity-mode)
    (sublimity-mode 1)))

(defun fr33splash-initial-buffer ()
  "Function to use as initial-buffer-choice."
   (fr33splash-create-buffer t))

(defun fr33splash-create-buffer (&optional initial)
  "Create or regenerate the splash buffer."
  (interactive)
  (let* ((buffer (get-buffer-create fr33splash-buffer-name)))
    (when (or (not fr33splash--content)
              (not initial))
      (fr33splash-regenerate-content))
    (fr33splash--apply-fixes)
    (fr33splash--redraw)
    (pop-to-buffer-same-window buffer)
    buffer))

(defun fr33splash--get-buffer ()
  "Get the fr33splash buffer."
  (get-buffer fr33splash-buffer-name))

(defun fr33splash--redraw (&rest _)
  "Regenerate and redraw the splash buffer."
  (when-let* ((buffer (fr33splash--get-buffer))
              (window (get-buffer-window buffer))
              (width (window-body-width window))
              (height (window-body-height window))
              (size (cons width height))
              ((not (equal fr33splash--last-size size))) ; Early exit
              (content (string-trim fr33splash--content))
              (content-lines (string-lines content))
              (inhibit-read-only t))
    (setq fr33splash--last-size size)
    (with-current-buffer buffer
      (erase-buffer)

      ;; Horizontal alignment
      (setq content (mapconcat (lambda (line)
        (let* ((len (length line))
               (padding-width (max 0 (floor (/ (- width len) 2))))
               (padding (make-string padding-width ?\s)))
          (if (<= width len)
            (let (( trim (/ (- len width) 2) ))
              (setq line (substring line trim (- len 1 trim)))))
          (concat padding line "\n")))
        content-lines))

      ;; Vertical alignment
      (let* ((n-lines (length content-lines))
             (padding-height (max 0 (floor (/ (- height n-lines) 2))))
             (padding (make-string padding-height ?\n)))
        (setq content (concat padding content)))

      (save-excursion (insert content))
      (fr33splash-mode))))

(defun fr33splash--visible ()
  "Determine if fr33splash buffer is visible in any window."
  (let ((visible nil))
    (walk-windows (lambda (w)
      (when (string-equal (buffer-name (window-buffer w))
                          fr33splash-buffer-name)
        (setq visible t))))
  visible))

(defun fr33splash--on-window-buffer-change (_)
  "Dominate the window or bury, depending on if splash is visible."
  (let ((kill-own-window nil)
        (kill-own-buffer nil))
    (when-let* ((buffer (fr33splash--get-buffer)))
      (if (fr33splash--visible)
        (walk-windows (lambda (window)
          (when-let* (((not kill-own-buffer))
                      (other-buffer (window-buffer window))
                      ((not (eq buffer other-buffer)))
                      ((not (minibufferp other-buffer)))
                      (name (buffer-name other-buffer)))
            (when (not (member name fr33splash--allow-overlap-buffer-names))
              (setq kill-own-buffer t)
              (setq kill-own-window t)))))
        (fr33splash--remove-fixes)
        (when (eq (window-old-buffer) buffer)
          (setq kill-own-buffer t)))
      (when kill-own-window
        (delete-window (get-buffer-window buffer)))
      (when kill-own-buffer
        (kill-buffer buffer)))))

(add-hook 'window-size-change-functions 'fr33splash--redraw)
(add-hook 'window-buffer-change-functions 'fr33splash--on-window-buffer-change)
#+END_SRC

** Extra

If you were going to export this all as a library, you should probably
exclude this stuff.

*** Setup

#+BEGIN_SRC emacs-lisp
(setq fr33splash-content-fn #'fr33splash-generate-content)
(setq initial-buffer-choice 'fr33splash-initial-buffer)

(defun fr33splash-advice-prevent-splitting (orig-fun &rest args)
  (if (fr33splash--visible)
    (message "Cannot split splash screen.")
    (apply orig-fun args)))
(advice-add 'my:split-window-right :around #'fr33splash-advice-prevent-splitting)
(advice-add 'my:split-window-below :around #'fr33splash-advice-prevent-splitting)
#+END_SRC

*** Color functions

Ripped off from kurecolor, obviously.

#+BEGIN_SRC emacs-lisp
(defun kurecolor-to-8bit (n)
  "Convert N (`0.0..1.0') to `0-255'."
  (* n 255.0))

(defun kurecolor-hex-to-rgb (hex)
  "Convert a `rgb' HEX color to a list `(r g b)'.

The `r',`g',`b' values range between `0.0..1.0'."
  (setq hex (replace-regexp-in-string "#" "" hex))
  (mapcar #'(lambda (s) (/ (string-to-number s 16) 255.0))
          (list (substring hex 0 2)
                (substring hex 2 4)
                (substring hex 4 6))))

(defun kurecolor-rgb-to-hex (rgb)
  "RGB as a list `(r g b)' to `rgb' hex color.

The `r',`g',`b' values can range between `0.0..1.0'."
  (cl-destructuring-bind
      (red green blue)
      (mapcar 'kurecolor-to-8bit rgb)
    (format "#%02X%02X%02X" red green blue)))
#+END_SRC

*** Utility

#+BEGIN_SRC emacs-lisp
(setq fr33splash-random-quip "")
(setq fr33splash--colors '(nil))
(setq fr33splash--color-groups (vector
  (vector 'pink)
  (vector 'mauve)
  (vector 'red 'maroon)
  (vector 'peach)
  (vector 'yellow)
  (vector 'green)
  (vector 'teal 'sky 'sapphire 'blue)))

(require 'color)
(defun fr33splash-randomize ()
  (setq fr33splash-random-quip
    (aref fr33splash-quips (random (length fr33splash-quips))))

  (let* ((color-group (aref fr33splash--color-groups
                            (random (length fr33splash--color-groups))))
         (color (aref color-group
                      (random (length color-group))))
         (fg (kurecolor-hex-to-rgb (catppuccin-get-color color)))
         (bg (kurecolor-hex-to-rgb (catppuccin-get-color 'mantle))))
    (setq fr33splash--colors
      (mapcar (lambda (rgb) (kurecolor-rgb-to-hex rgb)) (list
        bg ; bg
        fg ; text-fg
        (color-blend fg bg 0.16) ; text-bg
        (color-blend fg bg 0.08) ; panel
)))))

(defmacro fr33splash-let-colors (&rest body)
 `(seq-let (bg text-fg text-bg panel) fr33splash--colors
     ,@body))

;; TODO inhibit error messages?
(defun fr33splash--color-banner (&rest banner)
  (setq banner (mapconcat (lambda (b) b) banner "\n"))
  (dolist (chars '(("X" . "\U0001FB4A") ("Y" . "\U0001FB3F") ("Z" . "\u2585")
                   ("x" . "\U0001FB65") ("y" . "\U0001FB5A") ("z" . "\U0001FB84")
                   ("A" . "\U0001FB44") ("B" . "\U0001FB4F") ("C" . "\U0001FB60")))
    (setq banner (string-replace (car chars) (cdr chars) banner)))

  (let ((banner-chars (string-to-vector banner)))
    (fr33splash-let-colors
      (dotimes (i (length banner))
        (let* ((c (aref banner-chars i))
               (default-face `(:foreground ,panel
                               :background ,bg))
               (box-drawing-face-top `(:foreground ,panel
                                       :background ,bg
                                       :underline (:position t)))
               (box-drawing-face-bottom `(:foreground ,panel
                                          :background ,bg
                                          :underline (:position 19)))
               ; HACK Magic number (font height - 1)          ^^^^^

               (colors  (cond
                 ((char-equal c ?@) `(:foreground ,text-fg :background ,text-bg))
                 ((char-equal c ?!) `(:foreground ,text-fg :background ,text-bg :weight bold))
                 ((char-equal c ?:) `(:foreground ,text-fg :background ,text-bg :weight bold))
                 ((char-equal c ?.) `(:foreground ,text-fg :background ,text-bg))
                 ((char-equal c ?-) `(:foreground ,panel :background ,panel))
                 ((char-equal c ?_) `(:foreground ,bg :background ,bg))
                 ((char-equal c ?\U0001FB4A) box-drawing-face-top)    ; X
                 ((char-equal c ?\U0001FB3F) box-drawing-face-top)    ; Y
                 ((char-equal c ?\u2585)     box-drawing-face-top)    ; Z
                 ((char-equal c ?\U0001FB65) box-drawing-face-bottom) ; x
                 ((char-equal c ?\U0001FB5A) box-drawing-face-bottom) ; y
                 ((char-equal c ?\U0001FB84) box-drawing-face-bottom) ; z
                 ((char-equal c ?\U0001FB44) box-drawing-face-top)    ; A
                 ((char-equal c ?\U0001FB4F) box-drawing-face-top)    ; B
                 ((char-equal c ?\U0001FB60) box-drawing-face-bottom) ; C
                 (default-face))))
          (put-text-property i (1+ i) 'face colors banner)))))
  banner)
#+END_SRC

** Content

#+BEGIN_SRC emacs-lisp
(defun fr33splash-generate-content ()
  (fr33splash-randomize)
  (fr33splash-let-colors
  (concat
      (fr33splash--color-banner
        "_XZZZZZZY__XZZZZZZY__XZZZZZY__XZZZZZY__XZZZZZZZZZY__XZZZZZZY__XZZZZZZY__XZZZZZY_"
        "A-@@@@@@----@@@@@@----@@@@@----@@@@@----@@@@@@@@@----@@@@@@----@@@@@@----@@@@@-B"
        "-@@@@@@@@--@@@@@@@@--@@@@@@@--@@@@@@@--@@@@@@@@@@@--@@@@@@@@--@@@@@@@@--@@@@@@@-"
        "-@@!-------@@!--@@@------@@@------@@@--@@!-@@!-@@!--@@!--@@@--!@@------!@@------"
        "-!@!-------!@!--@!@------@!@------@!@--!@!-!@!-!@!--!@!--@!@--!@!-------!@!-----"
        "-@!!!:!:---@!@!!@!---@!@!!@---@!@!!@---@!!-!!@-@!@--@!@!@!@!--!@!-------!!@@!!--"
        "-!!!!!::---!!@!@!----!!@!@!---!!@!@!---!@!---!-!@!--!!!@!!!!--!!!--------!!@!!!-"
        "-!!:-------!!:-:!!-------!!:------!!:--!!:-----!!:--!!:--!!!--:!!-----------!:!-"
        "-:!:-------:!:--!:!------:!:------:!:--:!:-----:!:--:!:--!:!--:!:-----------!:!-"
        "-.::--y_x--::.--:::--::.::::--::.::::--:::-y_x-::.--::---:::--.:::..::--::::.::-"
        "-.:.--___--.:.--:.:---:.:.:----:.:.:---.:.-___-:..--.:---:.:---::.::.:--::.:.:-C"
        "xzzzzy___xzzzzzzzzzy_xzzzzzy__xzzzzzy_xzzzy___xzzzzzzzy_xzzzy_xzzzzzzzzzzzzzzzy_")
      "\n"
      "\n"
      (fr33splash--color-banner "XZZZZZZZZZZZZZY")
      "\n"
      (propertize "(o'_')o     " 'face `(:foreground ,text-fg))
      (propertize "  PRESS SPACE  " 'face `(:foreground ,text-fg :background ,panel :weight bold))
      (propertize "     t('.'t)" 'face `(:foreground ,text-fg))
      "\n"
      (fr33splash--color-banner "xzzzzzzzzzzzzzy")
      "\n\n"
      (propertize fr33splash-random-quip 'face `(:foreground ,(catppuccin-get-color 'surface0)))
)))

(setq fr33splash-quips (vector
  "WHEN?  WILL?  YOU?  CRACK?"
  "OPENYOUREYES OPENYOUREYES OPENYOUREYES"
  "Nothing... nothing... left... in... side..."
  "Have you noticed we're still waiting?"
  "You're the only human, everyone's an alien but you."
  "Head removal specialist - Free headectomy consultations!\n1-800-NO-HEAD"
  "There's no finer sound than when you left off a nine round."
  "WHERE'S MY CRUCIFIX? I CAN'T DIE WITHOUT IT!"
  "Born without eyes, hands, and half a brain...\nBe born addicted... TO COCAINE!"
  "((((((((((((((((((((emac))))))))))))))))))))"
  "C  Y  K  A    B  L  Y  A  T"
  "who up %s they %s"
  "No pain... no pain..."
  "C-k m s : save-buffer-kill-self"
  "+6209 -34 | 82 files changed"
  "git commit -m \"please work\""
  "I'm always tired, I'm always at least half asleep :)"
  "Everything's coming to a grinding halt."
  "Punch in late, and they DOCK YA!"
  "Come back with a warrant."
  "Run it into the ground."
  "Has anyone really been far even as decided to use even go want to do look more like?"
  "FOR NOTHING  -  AGAINST EVERYTHING"
  "!  TERROR LEVEL INCREASED  !"
  "No human being deserves to get what's coming to them."
  "0.1 + 0.2 = 0.30000000000000004"
))
#+END_SRC

* My library

*Notice*: Not all functions are defined in this section. There are
some less general / more context-specific functions that are scattered
around with no particular rhyme or reason.

** Advice

#+BEGIN_SRC emacs-lisp
(defun my:advice:be-quiet (orig-fun &rest args)
  "Advice function: Suppress messages in ORIG-FUN.

Example:

(advice-add 'svg-tag-mode-on :around #'my:advice:be-quiet)"
  (let ((inhibit-message t)
        (message-log-max nil))
    (apply orig-fun args)))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defun my:advice:nav-flash-show (&rest _)
  "Advice function: Call `nav-flash-show' after a command.

Example:

(advice-add 'avy-goto-char :after #'my:advice:nav-flash-show)"
  (nav-flash-show))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defun my:advice:always-force-save (&rest _)
  (my:fix-whitespace)
  (set-buffer-modified-p t))

(advice-add 'save-buffer :before #'my:advice:always-force-save)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defun my:advice:save-after-code-actions (&rest _)
  (save-buffer))

(advice-add 'lsp-ui-sideline-apply-code-actions :after #'my:advice:save-after-code-actions)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defun my:advice:bufler-list-center-header (&rest _)
  (with-current-buffer (get-buffer-create "*Bufler*")
    (let (( n (max (/ (- (frame-width) sublimity-attractive-centering-width) 2) 0)))
      (message "bufler-list called with args %s" n)
      (setf header-line-format
            (concat (make-string n (string-to-char " ")) header-line-format)))))

(advice-add 'bufler-list :after #'my:advice:bufler-list-center-header)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defun my:advice:imenu-list-close-after-goto (&rest _)
  (with-current-buffer (get-buffer-create "*Ilist*")
    (kill-buffer-and-window)))

(advice-add #'imenu-list--goto-entry :after 'my:advice:imenu-list-close-after-goto)
#+END_SRC

** Timing

- TODO Add ~debounce-eval-immediately~

#+BEGIN_SRC emacs-lisp
(setq my:debounce-timers (make-hash-table :test 'equal))
(defun my:debounce (name secs form)
  "Begin a timer for SECS seconds named NAME to delay the evaluation
of FORM, typically to prevent something expensive from running
too frequently. If a pending debounce timer exists with the same
NAME it is cancelled and replaced.

Example:

(my:debounce \"print-it\" 0.5 '(print \"it\"))"
  (if-let ((old-timer (map-elt my:debounce-timers name)))
          (cancel-timer old-timer))
  (let* ((new-timer-fn `(progn
          (setq my:debounce-timers (map-delete my:debounce-timers ,name))
          (eval ,form)))
         (new-timer (run-with-timer secs nil 'eval new-timer-fn)))
        (map-put! my:debounce-timers name new-timer)))
#+END_SRC

** Windows

This function was adapted from [[https://stackoverflow.com/questions/1832597][a Stack Overflow answer]] by [[https://stackoverflow.com/users/1762276/zhro][Zhro]].

#+BEGIN_SRC emacs-lisp
(defun my:delete-window-maybe-kill-buffer (&optional window)
  "Delete the window.
If WINDOW is nil, delete the current window.
If no other window shows its buffer, kill the buffer too."
  (interactive)
  (let ((buf (window-buffer window)))
    (if (> (length (window-list)) 1)
        (delete-window window)
      (unless (get-buffer-window buf 'visible) (kill-buffer buf))
      (kill-buffer buf))))
#+END_SRC

Switch to new window after split.

#+BEGIN_SRC emacs-lisp
(defun my:split-window-right ()
  (interactive)
  (split-window-right)
  (other-window 1))

(defun my:split-window-below ()
  (interactive)
  (split-window-below)
  (other-window 1))
#+END_SRC

It's irritating to need to switch to a temporary window to close
it. These functions are used to make closing temporary windows more
convenient.

#+BEGIN_SRC emacs-lisp
(defun my:temporary-window-p (&optional window)
  "Decide if the window is temporary.
If WINDOW is nil, use the current window."
  (let ((buffer (window-buffer window)))
    (with-current-buffer buffer
      (not (or (buffer-file-name buffer)
               (-contains? my:not-temporary-major-modes major-mode)
               (--some (-contains? my:not-temporary-minor-modes it)
                       local-minor-modes))))))

(defun my:delete-window (window)
  "Delete WINDOW or abort if WINDOW is a minibuffer."
  (if (window-minibuffer-p window)
      (abort-recursive-edit)
      (my:delete-window-maybe-kill-buffer window)))

(defun my:next-temporary-window ()
  "Attempt to find a minibuffer first. If no minibuffer is found,
then starting at the current window, find the next temporary
window."
  (interactive)
  (if-let ((minibuffer (active-minibuffer-window)))
    minibuffer
    (-first #'my:temporary-window-p (window-list))))

(defun my:delete-next-temporary-window ()
  "Starting at the current window, find the next temporary window
and delete it."
  (interactive)
  (if-let ((window (my:next-temporary-window)))
    (my:delete-window window)))

(defun my:delete-next-temporary-window-or-kb-quit ()
  "Starting at the current window, find the next temporary window
and delete it. If there is none, send keyboard-quit instead."
  (interactive)
  (if-let ((window (my:next-temporary-window)))
    (my:delete-window window)
    (keyboard-quit)))
#+END_SRC

When a window's major or minor mode matches any in these lists, that
window will never be considered temporary.

#+BEGIN_SRC emacs-lisp
(setq my:not-temporary-major-modes
  '(fr33splash-mode lisp-interaction-mode eat-mode))

(setq my:not-temporary-minor-modes
  '(org-src-mode))
#+END_SRC

** Buffers

Working on a project with a lot of files can get annoying.

#+BEGIN_SRC emacs-lisp
(defun my:kill-all-buffers ()
  (interactive)
  (mapc 'kill-buffer (buffer-list)))
#+END_SRC

** Errors

#+BEGIN_SRC emacs-lisp
(defun my:fix-next-error ()
  "Jump to the next error and open code actions"
  (interactive)
  (next-error)
  (call-interactively 'my:choose-point-action)
  (save-buffer))

(defun my:fix-previous-error ()
  "Jump to the previous error and open code actions"
  (interactive)
  (previous-error)
  (call-interactively 'my:choose-point-action)
  (save-buffer))
#+END_SRC

** Major-mode setup

#+BEGIN_SRC emacs-lisp
(defmacro my:set-formatter (major-mode lang-name formatter)
  (let ((hook (intern (concat (symbol-name major-mode) "-hook"))))
  `(add-hook ',hook (lambda ()
     (setq-local format-all-formatters '((,lang-name ,formatter)))))))
#+END_SRC

** Code actions

Code actions are provided by ~lsp-mode~ and ~lsp-ltex-plus~ via
different commands, this bridges the gap between them.

#+BEGIN_SRC emacs-lisp
(setq my:point-action-sources
   '((:name "English (ltex-ls-plus)"
      :action lsp-ltex-plus-actions
      :check lsp-ltex-plus--actions-here)
     (:name "Code actions (lsp-mode)"
      :action lsp-ui-sideline-apply-code-actions
      :check (lambda () lsp-ui-sideline--code-actions))))

(defun my:--action-source-p (src)
 (let ((inhibit-message t))
   (not (null (ignore-errors (funcall (plist-get src :check)))))))

(defun my:choose-point-action ()
  (interactive)
  (let (( sources (seq-filter #'my:--action-source-p my:point-action-sources)))
    (if sources
      (if (= 1 (length sources))
        (call-interactively (plist-get (car sources) :action))
        (let (( choice (completing-read "Action source: "
                          (seq-map (lambda (src) (plist-get src :name)) sources))))
          (dolist (src sources)
            (if (string-equal choice (plist-get src :name))
              (call-interactively (plist-get src :action)))))))))
#+END_SRC

* Backups

Prevent clobbering symlinks.

#+BEGIN_SRC emacs-lisp
(setq backup-by-copying t)
#+END_SRC

Use versioned backups.

#+BEGIN_SRC emacs-lisp
(setq version-control t)
#+END_SRC

Prevent backup files from being littered all over the place.

#+BEGIN_SRC emacs-lisp
(setq backup-directory-alist
      '(("." . "~/.emacs-backups/")))
#+END_SRC

Delete excess backup versions silently.

#+BEGIN_SRC emacs-lisp
(setq delete-old-versions t
      kept-new-versions 6
      kept-old-versions 2)
#+END_SRC

* Key bindings

** Hydras

Pretty-hydra is used to create action menus. I've chosen to use hydras
as the foundation for my custom keybind scheme to improve
discoverability and reduce cognitive load.

#+BEGIN_SRC emacs-lisp
(use-package major-mode-hydra
  :ensure t)

(use-package pretty-hydra
  :ensure t
  :custom (lv-use-padding t)
  :config
  (set-face-attribute 'hydra-face-red nil
    :foreground (catppuccin-get-color 'red))
  (set-face-attribute 'hydra-face-blue nil
    :foreground (catppuccin-get-color 'sapphire))
  (set-face-attribute 'hydra-face-pink nil
    :foreground (catppuccin-get-color 'pink))
  (set-face-attribute 'hydra-face-teal nil
    :foreground (catppuccin-get-color 'teal))
  (set-face-attribute 'hydra-face-amaranth nil
    :foreground (catppuccin-get-color 'mauve))
    ;; <config>
#+END_SRC

*Notice*: Not all hydras are defined in this section. Other sections
that define hydra(s):

- [[*Avy][Motion > Avy]]
- [[*Org][Languages > Org]]
- [[*Magit][Version Control > Magit]]
- [[*Rust][Languages > Rust]]

#+BEGIN_SRC emacs-lisp
(defun my:fix-hydras ()
  (setq-local sublimity-attractive-centering-width 0)
  (setq-local cursor-type nil)
  (setq-local evil-default-cursor (list nil)))
(add-hook 'lv-window-hook 'my:fix-hydras)

(defun my:pad-hydras (orig-fun format-string &rest args)
  (let* ((len (length (car (string-lines format-string))))
        (padding (make-string len ?\s)))
    (apply orig-fun
           (concat padding
                   "\n"
                   format-string
                   (propertize "." 'face `(:foreground ,(catppuccin-get-color 'mantle))))
           args)))
(advice-add 'lv-message :around #'my:pad-hydras)
#+END_SRC

*** Help

#+BEGIN_SRC emacs-lisp
(pretty-hydra-define hydra:help
  (:exit t :idle 0.25)
  ("Describe"
   (("v" describe-variable "Variable")
    ("f" describe-function "Function")
    ("s" describe-face     "Face")
    ("m" describe-mode     "Mode")
    ("k" describe-key      "Key"))
   "Find"
   (("V" find-variable        "Variable")
    ("F" find-function        "Function")
    ("S" find-face-definition "Face"))
   "Evaluate"
   (("e" eval-expression "Expression")
    ("r" eval-region     "Region")
    ("b" eval-buffer     "Buffer")
    ("d" eval-defun      "Defun")
    ("x" eval-last-sexp  "Sexp"))
   "Set"
   (("=" set-variable   "Variable"))))
#+END_SRC

*** Code

#+BEGIN_SRC emacs-lisp
(pretty-hydra-define hydra:code
  (:exit t :idle 0.25)
  ("Action"
   (("c" project-compile              "Compile project")
    ("C" project-recompile            "Recompile project")
    ("." my:choose-point-action       "Code actions at point")
    ("/" comment-dwim                 "Comment code")
    ("o" lsp-organize-imports         "Organize imports")
    ("r" lsp-rename                   "Rename symbol"))
   "Find"
   (("n" next-error                   "Next error"     :exit nil)
    ("p" previous-error               "Previous error" :exit nil)
    ("d" lsp-ui-peek-find-definitions "Definitions")
    ("R" lsp-ui-peek-find-references  "References"))))
#+END_SRC

*** File

#+BEGIN_SRC emacs-lisp
(pretty-hydra-define hydra:file
  (:exit t :idle 0.25)
  ("Switch"
   (("f" find-file         "Find file")
    ("p" project-find-file "Find file in project"))))
#+END_SRC

*** Buffer

#+BEGIN_SRC emacs-lisp
(defun my:last-buffer ()
  (interactive)
  (switch-to-buffer (other-buffer (current-buffer) 1)))

(pretty-hydra-define hydra:buffer
  (:exit t :idle 0.25)
  ("Switch"
   (("b" consult-buffer                  "Quick switch")
    ("i" bufler-list                     "List buffers")
    ("]" next-buffer                     "Next buffer"     :exit nil)
    ("[" previous-buffer                 "Previous buffer" :exit nil)
    ("l" my:last-buffer                  "Last buffer")
    ("m" (switch-to-buffer "*Messages*") "Messages")
    ("S" (scratch-buffer)                "Scratch"))
   "Actions"
   (("s" save-buffer         "Save buffer")
    ("k" kill-current-buffer "Kill buffer")
    ("K" kill-buffer         "Kill other buffer")
    ("X" my:kill-all-buffers "Kill all buffers")
    ("r" revert-buffer       "Revert current buffer")
    ("R" rename-buffer       "Rename current buffer"))))
#+END_SRC

*** Window

#+BEGIN_SRC emacs-lisp
(pretty-hydra-define hydra:window
  (:exit t :idle 0.25)
  ("Switch"
   (("w" my:switch-window "Quick switch"))
   "Actions"
   (("k" delete-window             "Kill window")
    ("K" switch-window-then-delete "Kill other window")
    ("X" delete-other-windows      "Kill all other windows")
    ("b" balance-windows           "Balance windows")
    ("s" my:split-window-below     "Split window horizontally")
    ("v" my:split-window-right     "Split window vertically"))))
#+END_SRC

*** Toggle

#+BEGIN_SRC emacs-lisp
(pretty-hydra-define hydra:toggle
  (:exit t :idle 0.25)
  ("Toggle"
   (("w" visual-line-mode           "Line wrapping" :toggle t)
    ("h" lsp-inlay-hints-mode       "LSP: Inlay hints" :toggle t)
    ("p" org-toggle-pretty-entities "Org: Pretty entities" :toggle org-pretty-entities))))
#+END_SRC

*** Find

#+BEGIN_SRC emacs-lisp
(pretty-hydra-define hydra:find
  (:exit t :idle 0.25)
  ("Consult"
   (("<tab>" my:consult-imenu-or-org-heading "Imenu / Org headings")
    ("i"     consult-imenu-multi             "Project Imenu")
    ("o"     consult-outline                 "Outline")
    ("l"     consult-line                    "Line")
    ("L"     consult-line-multi              "Line in project")
    ("h"     consult-org-heading             "Headings")
    ("b"     consult-buffer                  "Buffer")
    ("g"     consult-ripgrep                 "Ripgrep")
    ("e"     consult-flycheck                "Flycheck errors")
    ("r"     consult-recent-file             "Recent files"))
  ("Show"
   (("O"     symbols-outline-show            "Symbols outline")
    ("I"     imenu-list-smart-toggle         "Imenu list")))))
#+END_SRC

*** Leader key

#+BEGIN_SRC emacs-lisp
(pretty-hydra-define hydra:leader
  (:exit t :idle 0.25)
  ("Hydra"
   (("<tab>" hydra:find/body     "Find")
    ("m"     major-mode-hydra    "Mode-specific")
    ("t"     hydra:toggle/body   "Toggle")
    ("a"     hydra:avy/body      "Avy")
    ("c"     hydra:code/body     "Code")
    ("f"     hydra:file/body     "File")
    ("b"     hydra:buffer/body   "Buffer")
    ("w"     hydra:window/body   "Window")
    ("h"     hydra:help/body     "Help & more")
    ("r"     hydra:org-roam/body "Org Roam"))
   "Shortcut"
   (("SPC"   project-find-file       "Find file in project")
    ("`"     eat-other-window        "Terminal")
    ("/"     comment-dwim            "Comment code")
    ("."     my:choose-point-action  "Code actions at point")
    (">"     my:fix-next-error       "Fix next error")
    ("<"     my:fix-previous-error   "Fix previous error")
    ("g"     magit                   "Open Magit")
    ("s"     save-buffer             "Save buffer")
    ("q"     save-buffers-kill-emacs "Save & quit"))))
) ;; </config>
#+END_SRC

** General

General provides a convenient way to bind keys.

#+BEGIN_SRC emacs-lisp
(use-package general
  :ensure t
  :init
  (setq general-override-states
        '(insert emacs hybrid normal visual motion operator replace))
  :config
  ;; <config>
#+END_SRC

Use escape to close temporary windows.

#+BEGIN_SRC emacs-lisp
  (general-define-key
    :keymaps 'minibuffer-mode-map
    (kbd "<escape>") 'abort-minibuffers)

  (general-define-key
    :states '(normal)
    :keymaps 'override
    (kbd "<escape>") 'my:delete-next-temporary-window)
#+END_SRC

Use spacebar to open the [[*Leader key][Leader key hydra]].

#+BEGIN_SRC emacs-lisp
  (general-define-key
    :states '(normal visual motion)
    :keymaps 'override
    "SPC" 'hydra:leader/body))
;; </config>
#+END_SRC

** Which-key

Which-key shows all the possible completions of a partially-input
keybind.

#+BEGIN_SRC emacs-lisp
(use-package which-key
  :ensure t
  :delight
  :config
  (which-key-mode))
#+END_SRC

* Evil

Evil (extensible vi layer) emulates the main features of Vim.

#+BEGIN_SRC emacs-lisp
(use-package evil
  :ensure t
  :init
  (setq evil-default-cursor t
        evil-want-keybinding nil
        evil-want-C-u-scroll t
        evil-undo-system 'undo-redo)
  :config
  (evil-mode 1)
;; <config>
#+END_SRC

Prevent shifting text from clearing selection:

#+BEGIN_SRC emacs-lisp
  (define-key evil-visual-state-map (kbd ">") 'my:evil-shift-right-visual)
  (define-key evil-visual-state-map (kbd "<") 'my:evil-shift-left-visual)

  (defun my:evil-shift-left-visual ()
    (interactive)
    (evil-shift-left (region-beginning) (region-end))
    (evil-normal-state)
    (evil-visual-restore))

  (defun my:evil-shift-right-visual ()
    (interactive)
    (evil-shift-right (region-beginning) (region-end))
    (evil-normal-state)
    (evil-visual-restore)))
;; </config>
#+END_SRC

Evil collection is a collection of Evil bindings for the parts of
Emacs that Evil does not cover properly by default.

#+BEGIN_SRC emacs-lisp
(use-package evil-collection
  :ensure t
  :after evil
  :custom
  (evil-collection-want-unimpaired-p nil)
  :init
  (evil-collection-init))
#+END_SRC

* Completion
** Orderless

The orderless completion style divides the pattern into
space-separated components and matches candidates that match all the components in any order.

#+BEGIN_SRC emacs-lisp
(use-package orderless
  :ensure t
  :custom
  (completion-styles '(orderless basic))
  (completion-category-overrides '((file (styles partial-completion)))))
#+END_SRC

** Company

#+BEGIN_SRC emacs-lisp
(use-package yasnippet
  :ensure t
  :delight yas-minor-mode
  :hook ((lsp-mode . yas-minor-mode)))

(use-package company
:ensure t
:delight
:custom
(company-idle-delay 0.1))
#+END_SRC

* Minibuffer
** Vertico

Vertico is a minibuffer completion interface.

#+BEGIN_SRC emacs-lisp
(use-package vertico
  :ensure t
  :init
  (vertico-mode)
  :config
  (setq vertico-cycle t)
  :bind (:map vertico-map
         ("C-j" . vertico-next)
         ("C-k" . vertico-previous)
         ("TAB" . vertico-insert)))
#+END_SRC

Persist history over Emacs restarts. Vertico sorts by history
position.

#+BEGIN_SRC emacs-lisp
(use-package savehist
  :init
  (savehist-mode))
#+END_SRC

Do not allow the cursor in the minibuffer prompt.

#+BEGIN_SRC emacs-lisp
(use-package emacs
  :init
  (setq minibuffer-prompt-properties
        '(read-only t cursor-intangible t face minibuffer-prompt))
  (add-hook 'minibuffer-setup-hook #'cursor-intangible-mode)
  ;; <init>
#+END_SRC

Hide commands in M-x which do not work in the current mode. Vertico
commands are hidden in normal buffers.

#+BEGIN_SRC emacs-lisp
  (setq read-extended-command-predicate
        #'command-completion-default-include-p))
;; </init>
#+END_SRC

** Marginalia

Marginalia adds helpful information to entries in Vertico. For
example, if you type ~M-x~, Vertico will open a list of usable
commands. Marginalia will add each command's description next to it.

#+BEGIN_SRC emacs-lisp
(use-package marginalia
  :ensure t
  :init
  (marginalia-mode))
#+END_SRC

* Mode line

For unknown reasons, mini-modeline-enhance-visual breaks theming on emacsclient.

#+BEGIN_SRC emacs-lisp
(use-package mini-modeline
  :ensure t
  :delight mini-modeline-mode
  :init
  (mini-modeline-mode t)
  :custom
  (mini-modeline-display-gui-line t)
  (mini-modeline-enhance-visual nil)
  (mini-modeline-right-padding 6))

(use-package delight
  :ensure t)

(use-package autorevert
  :delight auto-revert-mode)
#+END_SRC

* Motion
** Avy

Avy is a convenient tool to jump around and perform some actions based
on a short filter.

#+BEGIN_SRC emacs-lisp
(use-package avy
  :ensure t
  :after evil
  :config
  (setq avy-timeout-seconds 0.375)
  (advice-add 'avy-process :after #'my:advice:nav-flash-show))

(pretty-hydra-define hydra:avy
  (:exit t :idle 0.25)
  ("Filter"
   (("a" avy-goto-char-timer           "Char(s) with timer")
    ("c" avy-goto-char-in-line         "Char in line")
    ("w" avy-goto-word-1               "Word by first char")
    ("s" avy-goto-symbol-1             "Symbol by first char")
    ("h" avy-org-goto-heading-timer    "Org heading with timer"))
   "Repeat"
   ((";" avy-next                      "Next match"     :exit nil)
    ("," avy-previous                  "Previous match" :exit nil))
   "Actions"
   (("y" avy-copy-line                 "Copy line")
    ("Y" avy-copy-region               "Copy region")
    ("d" avy-kill-whole-line           "Delete line")
    ("D" avy-kill-region               "Delete region"))))
#+END_SRC

** Nav-flash

Nav-flash makes it easier to track the cursor across large movements
by flashing the current line.

#+BEGIN_SRC emacs-lisp
(use-package nav-flash
  :ensure t
  :config
  (setq nav-flash-delay 0.125)
  (set-face-attribute 'nav-flash-face nil
    :background (face-attribute 'cursor :background)
    :foreground (face-attribute 'default :background))

  (--map (advice-add it :after #'my:advice:nav-flash-show)
         '(evil-scroll-up evil-scroll-down)))
#+END_SRC

* Version control
** Magit

#+BEGIN_SRC emacs-lisp
(use-package magit
  :ensure t
  :init
  (with-eval-after-load 'magit-mode
    (add-hook 'after-save-hook 'magit-after-save-refresh-status t))
  :config
  (setq git-commit-style-convention-checks
        '(non-empty-second-line overlong-summary-line))
  (keymap-set transient-map "<escape>" #'transient-quit-one)

  (add-hook 'git-commit-setup-hook (lambda ()
    (whitespace-mode -1)
    (lsp-ltex-plus-mode -1))))
#+END_SRC

** diff-hl

#+BEGIN_SRC emacs-lisp
(use-package diff-hl
  :ensure t
  :hook
  (magit-post-refresh-hook . diff-hl-magit-post-refresh)
  (after-save-hook . magit-after-save-refresh-status)
  :init (global-diff-hl-mode))
#+END_SRC

* Search
** Symbols Outline

Show an outline of all the symbols in a code file.
The default indentation is hardcoded, so I have to replace the relevant function entirely.

#+BEGIN_SRC emacs-lisp
(use-package symbols-outline
  :ensure t
  :init
  (add-hook 'lsp-mode-hook (lambda ()
    (setq-local symbols-outline-fetch-fn #'symbols-outline-lsp-fetch)))
  :custom
  (symbols-outline-window-width 60)
  (symbols-outline-format-symbol-name-p nil)
  :config
  (evil-define-key 'motion symbols-outline-mode-map
    (kbd "RET") 'symbols-outline-visit-and-quit)

  (symbols-outline-follow-mode)

  (defun my:advice:symbols-outline--insert-line (orig-fun node depth)
    (let* ((name (symbols-outline-node-name node))
           (kind (symbols-outline-node-kind node))
           (face (symbols-outline--get-kind-face kind))
           (line (symbols-outline-node-line node))
           (lp (concat
                " "
                (make-string (* depth 3) ?\s) ; CHANGED
                (when (or (display-graphic-p)
                          symbols-outline-use-nerd-icon-in-tui)
                  (concat (symbols-outline--get-kind-icon (or kind "null"))
                          " ")))))
      (when (symbols-outline-node-children node)
        (if-let (ov (symbols-outline-node-ov node))
            (unless (eq (overlay-start ov) (point))
              (move-overlay ov (point) (point)))
          (setq ov (make-overlay (point) (point)))
          (setf (symbols-outline-node-ov node) ov))
        (overlay-put (symbols-outline-node-ov node) 'before-string
                     (symbols-outline--get-margin-spec-cache
                      (symbols-outline-node-collapsed node))))
      (insert (propertize (symbols-outline--format-symbol-name name)
                          'line line
                          'depth depth
                          'face face
                          'node node
                          'mouse-face 'highlight
                          'line-prefix lp))))

   (advice-add 'symbols-outline--insert-line :around #'my:advice:symbols-outline--insert-line))

#+END_SRC

** imenu-list

#+BEGIN_SRC emacs-lisp
(use-package imenu-list
  :ensure t
  :custom
  (imenu-list-focus-after-activation t)
  (imenu-sort-function #'imenu--sort-by-name)
  :config
  (set-face-foreground 'imenu-list-entry-face-0 (catppuccin-get-color 'mauve))
  (set-face-foreground 'imenu-list-entry-subalist-face-0 (catppuccin-get-color 'mauve))
  (set-face-foreground 'imenu-list-entry-face-1 (catppuccin-get-color 'text)))
#+END_SRC

** Consult

#+BEGIN_SRC emacs-lisp
(use-package consult :ensure t)
(use-package consult-flycheck :ensure t)
(use-package hl-todo :ensure t)
(use-package consult-todo :ensure t)

(defun my:consult-imenu-or-org-heading ()
  (interactive)
  (if (string= major-mode "org-mode")
      (consult-org-heading)
      (consult-imenu)))
#+END_SRC

* Whitespace

Tabs make me sick to my stomach.

#+BEGIN_SRC emacs-lisp
(setq indent-tabs-mode nil)
(setq whitespace-style '(face tabs trailing empty))
(global-whitespace-mode)

(eval-after-load 'whitespace '(let ((color (catppuccin-get-color 'peach)))
  (dolist (face '(whitespace-tab trailing-whitespace))
    (set-face-attribute face nil
      :background color
      :box `(:color ,color
             :line-width (-1 . -1))))))
#+END_SRC

Try to fix some things automatically.

#+BEGIN_SRC emacs-lisp
(defun my:fix-whitespace ()
  (save-excursion
    (untabify 0 (buffer-size))
    (delete-trailing-whitespace 0 (buffer-size))
    (flush-lines "^\s-*$" 0 (buffer-size))))

(add-hook 'before-save-hook #'my:fix-whitespace)
#+END_SRC

* Misc. Packages
** Eldoc

#+BEGIN_SRC emacs-lisp
(use-package markdown-mode)

(defun my:open-docs ()
  (call-interactively 'eldoc)
  (with-current-buffer (eldoc-doc-buffer)
    (markdown-view-mode)))

(use-package eldoc
  :after evil
  :delight
  :custom
  (global-eldoc-mode t)
  (eldoc-echo-area-use-multiline-p nil)
  (evil-lookup-func 'my:open-docs))
#+END_SRC

** Try

Try allows you to try Emacs packages without installing them.

#+BEGIN_SRC emacs-lisp
(use-package try :ensure t)
#+END_SRC

** Switch-window

Switch-window provides a nice way to choose which window to switch to
when there are more than two windows. When a switch-window command is
used, a number character appears in the corner of each window. Typing
one of the characters then switches focus to that window.

#+BEGIN_SRC emacs-lisp
(use-package switch-window
  :ensure t
  :init
  :config
  (defun my:switch-window ()
    "Switch window and change cursor color."
    (interactive)
    (set-cursor-color my:switch-window-cursor-color)
    (switch-window))
  (defun my:switch-window-finish-hook ()
    (set-cursor-color my:cursor-color))
  (add-hook 'switch-window-finish-hook #'my:switch-window-finish-hook)

  (setq switch-window-input-style 'minibuffer)
  (set-face-attribute 'switch-window-label nil :height 5.0))

(defun my:advice:always-show-switch-window-overlay (orig-fun &rest args)
  (setq switch-window-threshold 1)
  (apply orig-fun args)
  (setq switch-window-threshold 2))

(advice-add 'switch-window-then-delete :around #'my:advice:always-show-switch-window-overlay)
#+END_SRC

** Solaire mode

Solaire mode helps to visually distinguish "real" buffers (code
buffers) from "unreal" buffers (popups, sidebars, log buffers,
terminals, etc.) by giving the latter a different background.

#+BEGIN_SRC emacs-lisp
(use-package solaire-mode
  :ensure t
  :after general
  :config
  (solaire-global-mode +1))
#+END_SRC

** Bufler

Bufler is an ibuffer alternative.

#+BEGIN_SRC emacs-lisp
(use-package bufler
  :ensure t
  :after evil
  :config
  (add-hook 'bufler-list-mode-hook
    (lambda () (setq-local font-lock-unfontify-region-function #'ignore)))
  (evil-define-key 'motion bufler-list-mode-map
    (kbd "RET") 'bufler-list-buffer-switch
    (kbd "SPC") 'bufler-list-buffer-peek
    (kbd "C-s") 'bufler-list-buffer-save
    "d" 'bufler-list-buffer-kill
    "x" 'bufler-list-buffer-kill))
#+END_SRC

** WIP SVG tag mode

SVG tag mode replaces keywords or regular expression with SVG tags. It
can be used as an extra-fancy alternative to ~hl-todo~.

#+BEGIN_SRC emacs-lisp
(use-package svg-tag-mode
  :ensure t
  :config
  ;; <config>
#+END_SRC

Define some simple SVG tags. The regular expressions are
case-sensitive, so there's going to be some redundant patterns.

#+BEGIN_SRC emacs-lisp
  (defconst my:svg-tags '(
    ("\\(Example\\(?:s\\| [[:digit:]]+\\)?:?\\)" . blue)
    ; Example Examples Example: Examples: Example 16 Example 32:

    ("\\(Question\\(?:s\\| [[:digit:]]+\\)?:?\\)" . mauve)
    ; Question Questions Question: Questions: Question 16 Question 32:

    ("TODO"                 . sapphire) ; TODO
    ("WIP"                  . teal)     ; WIP
    ("DONE"                 . green)    ; DONE
    ("TEMP"                 . red)      ; TEMP
    ("\\(HACK:?\\)"         . mauve)    ; HACK HACK:
    ("\\(Hack:?\\)"         . mauve)    ; Hack Hack:
    ("\\(IMPORTANT[:!]?\\)" . peach)    ; IMPORTANT IMPORTANT! IMPORTANT:
    ("\\(Important[:!]?\\)" . peach)    ; Important Important! Important:
    ("WARN"                 . yellow)   ; WARN
    ("\\(Warning[:!]?\\)"   . yellow))) ; Warning Warning! Warning:
#+END_SRC

Example

Define the default style. It's necessary to use
~(getnix "tagsFontFamily")~ instead of ~(getnix "fontFamily")~ because my default
font causes some strange kerning issues.

#+BEGIN_SRC emacs-lisp
  (setq svg-lib-style-default `(
    :background ,(catppuccin-get-color 'text)
    :foreground ,(catppuccin-get-color 'base)
    :font-family (getnix "tagsFontFamily")
    :font-size (getnix "fontSize")
    :font-weight 800
    :padding 1
    :margin 0
    :stroke 0
    :radius 5.5
    :alignment 0.5
    :width 20
    :height 1.0
    :scale 1.0
    :ascent center
    :collection "material"))
#+END_SRC

Create the tags by mapping the previously defined alist of patterns
and color.

#+BEGIN_SRC emacs-lisp
  (setq svg-tag-tags (--map
    `(,(car it) . ((lambda (tag) (svg-lib-tag tag svg-lib-style-default
      :background ,(catppuccin-get-color (cdr it))))))
    my:svg-tags))
#+END_SRC

Add advice to suppress the constant "SVG tag mode on" messages.

#+BEGIN_SRC emacs-lisp
  (advice-add 'svg-tag-mode-on :around #'my:advice:be-quiet)
#+END_SRC

Finally, enable the SVG tags globally.

#+BEGIN_SRC emacs-lisp
  (global-svg-tag-mode))
;; </config>
#+END_SRC

*** TODO Add progress bar, tags, priority

[[https://github.com/rougier/svg-tag-mode/blob/main/examples/example-2.el]]

** Format-all

#+BEGIN_SRC emacs-lisp
(use-package format-all
  :ensure t
  :delight
  :hook (prog-mode . format-all-mode)
  :custom
  (format-all-show-errors 'never))
#+END_SRC

** LSP
#+BEGIN_SRC emacs-lisp
(use-package lsp-mode
  :ensure t
  :delight
  :after eldoc
  :hook ((lsp-mode . lsp-diagnostics-mode)
         (lsp-mode . lsp-enable-which-key-integration)
         (lsp-mode . company-mode))
  :custom
  (gc-cons-threshold 100000000)
  (read-process-output-max (* 1024 1024))

  (lsp-enable-on-type-formatting nil)
  (lsp-auto-execute-action nil)
  (lsp-headerline-breadcrumb-enable nil)
  (lsp-lens-enable nil)
  (lsp-diagnostics-provider :flycheck)
  (lsp-keep-workspace-alive nil)
  (lsp-enable-xref t)
  (lsp-auto-configure t)
  (lsp-eldoc-enable-hover t)
  (lsp-eldoc-render-all t)
  (lsp-enable-symbol-highlighting t))

(use-package lsp-ui
  :ensure t
  :after (lsp-mode evil)
  :bind (("C-K" . lsp-ui-doc-focus-frame))
  :custom
  (lsp-ui-peek-enable t)

  (lsp-ui-sideline-show-hover nil)
  (lsp-ui-sideline-show-diagnostics nil)
  (lsp-ui-sideline-show-code-actions t)

  (lsp-ui-doc-enable t)
  (lsp-ui-doc-include-signature t)
  (lsp-ui-doc-show-with-cursor nil)
  (lsp-ui-doc-show-with-mouse nil)
  (lsp-ui-doc-position 'at-point)
  (lsp-ui-doc-max-height 30)
  :config
  (set-face-foreground 'lsp-ui-sideline-code-action
                       (catppuccin-get-color 'surface2))
  (define-key evil-normal-state-map (kbd "K") 'lsp-ui-doc-glance))

#+END_SRC

** Flycheck

Flycheck is a modern on-the-fly syntax checking extension.

#+BEGIN_SRC emacs-lisp
(defun my:flycheck-annotate-format (err &optional include-snippet)
  (car (split-string
    (or (flycheck-error-message err)
      (format "Unknown %S" (flycheck-error-level err)))
    "\n")))

(defun my:set-flycheck-color (type fg-name bg)
  (let ((fg (catppuccin-get-color fg-name))
        (problem-text (intern (concat "flycheck-" type)))
        (annotation-fg (intern (concat "flycheck-annotate-" type)))
        (annotation-bg (intern (concat "flycheck-annotate-" type "-background"))))

    (set-face-background annotation-bg bg)
    (set-face-attribute annotation-fg nil
      :foreground fg :background bg)
    (set-face-attribute problem-text nil
      :underline `(:color ,fg :style wave)
      :weight 'bold)))


(use-package flycheck
  :ensure t
  :custom
  (flycheck-annotate-other-lines-style nil)
  (flycheck-annotate-current-line-style 'below)
  (flycheck-annotate-background t)
  (flycheck-indication-mode nil)
  (flycheck-annotate-format-function #'my:flycheck-annotate-format)
  :init
  (global-flycheck-mode)
  (global-flycheck-annotate-mode)

  ;                                     5% opacity
  (my:set-flycheck-color "error"   'red    "#453243")
  (my:set-flycheck-color "warning" 'yellow "#454144")
  (my:set-flycheck-color "info"    'mauve  "#3c3653"))
#+END_SRC

** Treesit-auto

Treesit-auto provides an easy way to automatically install and use
tree-sitter major modes.

#+BEGIN_SRC emacs-lisp
(use-package treesit-auto
  :ensure t
  :config
  (setq treesit-auto-install t)
  (global-treesit-auto-mode))
#+END_SRC

** Rainbow-delimiters

#+BEGIN_SRC emacs-lisp
(use-package rainbow-delimiters
  :ensure t
  :init (rainbow-delimiters-mode))
#+END_SRC

** TODO Dimmer

Gone until it's fixed:
https://github.com/gonewest818/dimmer.el/pull/88

#+BEGIN_SRC emacs-lisp
;; (use-package dimmer
;;   :ensure t
;;   :vc (:url "https://github.com/chrhansk/dimmer.el" :rev "9a75788")
;;   :init
;;   (dimmer-configure-which-key)
;;   (dimmer-configure-company-box)
;;   (dimmer-configure-hydra)
;;   (dimmer-configure-magit)
;;   (dimmer-configure-org)
;;   (dimmer-mode t))
#+END_SRC

** Sublimity

Centers each buffer horizontally and add smooth scroll.

#+BEGIN_SRC emacs-lisp
(use-package sublimity
  :ensure t
  :init (sublimity-mode 1)
  :config
  (add-to-list 'sublimity-disabled-major-modes 'flycheck-error-list-mode))

(use-package sublimity-attractive
  :after sublimity
  :custom
  (sublimity-attractive-centering-width 110))

(use-package sublimity-scroll
  :after sublimity)
#+END_SRC

** Eat

Eat is a terminal emulator. Works best with [[https://codeberg.org/akib/emacs-eat#:~:text=shell integration,-for][shell integration]].

#+BEGIN_SRC emacs-lisp
(use-package eat
    :ensure t)
#+END_SRC

* Languages
** English

#+BEGIN_SRC emacs-lisp
(use-package lsp-ltex-plus
  :ensure t
  :vc (:url "https://github.com/ltex-plus/emacs-ltex-plus" :rev :newest)
  :init (lsp-ltex-plus-enable-for-modes)
  :custom
  (lsp-ltex-plus-check-programming-languages t)
  (lsp-ltex-plus-diagnostics-provider 'flycheck))
#+END_SRC

** Emacs Lisp

#+BEGIN_SRC emacs-lisp
(use-package elisp-def :ensure t)

(use-package highlight-quoted
  :ensure t
  :config
  (add-hook 'emacs-lisp-mode-hook 'highlight-quoted-mode))
#+END_SRC

** Org

Org is like Markdown but a lot better.

#+BEGIN_SRC emacs-lisp
(use-package htmlize :ensure t)
(use-package org
  :ensure t
  :after evil htmlize
  :hook
  (org-mode . company-mode)
  :config
  ;; <config>
#+END_SRC

Append custom ~css~ to make exporting from ~org~ into ~html~ match our
editor theme.

#+BEGIN_SRC emacs-lisp
(setq org-html-head
    (concat "<style>" (getnix "exportCSS") "</style>"))
#+END_SRC

Change the default appearance of org documents.

#+BEGIN_SRC emacs-lisp
(setq org-indent-mode-turns-on-hiding-stars nil
      org-startup-indented t
      org-startup-folded 'nofold)

(set-face-attribute 'org-block nil
  :foreground my:code-color))
;; </config>
#+END_SRC

Fix odd indentation behavior in src blocks.

#+BEGIN_SRC emacs-lisp
(setq org-src-preserve-indentation t
      org-edit-src-content-indentation 0)
#+END_SRC

Change the ~HTML~ export preamble and postamble.

- TODO Figure out how to hide the title for HTML exports only.

#+BEGIN_SRC emacs-lisp
(setq org-export-with-title nil)
(setq org-html-preamble-format
      '(("en" "<h1 class=\"title\">%t</h1>\n<p class=\"author\">by %a</p>")))

(setq org-html-postamble t
      org-html-postamble-format '(("en" "<p class=\"date\">Export time: %T</p>")))

(setq org-todo-keywords
      '((sequence "TODO" "WIP" "|" "DONE")))
#+END_SRC

*** Roam

#+BEGIN_SRC emacs-lisp
(use-package org-roam
  :ensure t
  :custom (org-roam-directory (file-truename "~/org-roam"))
  :config
  (when (not (file-directory-p org-roam-directory))
    (make-directory org-roam-directory))

  (setq org-roam-node-display-template
        (concat "${title:*} " (propertize "${tags:10}" 'face 'org-tag)))

  (org-roam-db-autosync-mode)
  (require 'org-roam-protocol))
#+END_SRC

**** Hydra

#+BEGIN_SRC emacs-lisp
(pretty-hydra-define hydra:org-roam
  (:exit t :idle 0.25)
   ("Org Roam"
   (("b" org-roam-buffer-toggle       "Toggle buffer")
    ("g" org-roam-graph  "Graph")
    ("f" org-roam-node-find               "Find node")
    ("i" org-roam-node-insert  "Insert node")
    ("c" org-roam-capture  "Capture")

    ("d" org-roam-dailies-capture-today  "Capture today (dailies?)")


    )))
#+END_SRC

*** Hydra

#+BEGIN_SRC emacs-lisp
(defun my:org-toggle-emphasis-markers ()
  "Toggle emphasis markers [*/_=~+]"
  (interactive)
  (setq org-hide-emphasis-markers (not org-hide-emphasis-markers)))

(major-mode-hydra-define org-mode
  (:exit t :idle 0.25 :quit-key "<escape>")
  ("Toggle"
   (("l" org-toggle-link-display        "Link display")
    ("E" my:org-toggle-emphasis-markers "Emphasis markers")
    ("c" org-toggle-checkbox            "Checkbox")
    ("i" org-toggle-inline-images       "Inline images")
    ("n" org-toggle-narrow-to-subtree   "Narrow to subtree")
    ("p" org-toggle-pretty-entities     "Pretty entities" :toggle org-pretty-entities))
   "Insert"
   (("L" org-insert-link             "Link")
    ("s" org-store-link              "(Store link to here)")
    ("S" org-insert-last-stored-link "Last stored link")
    ("t" org-time-stamp              "Timestamp")
    ("d" org-insert-drawer           "Drawer")
    ("T" org-table-create            "Table"))
   "Table"
   (("a" org-table-align         "Align")
    ("R" org-table-insert-row    "Insert row"    :exit nil)
    ("C" org-table-insert-column "Insert column" :exit nil)
    ("k" org-table-kill-row      "Kill row")
    ("K" org-table-kill-column   "Kill column"))
   "Hydra"
   (("e" hydra:org-emphasize/body "Emphasize"))))

(pretty-hydra-define hydra:org-emphasize
  (:exit t :idle 0.25)
  ("Mnemonic"
   (("x" (org-emphasize ?\s) "Clear")
    ("b" (org-emphasize ?*)  "Bold")
    ("i" (org-emphasize ?/)  "Italic")
    ("u" (org-emphasize ?_)  "Underlined")
    ("v" (org-emphasize ?=)  "Verbatim")
    ("c" (org-emphasize ?~)  "Code")
    ("s" (org-emphasize ?+)  "Strike-through"))
   "Literal"
   (("*" (org-emphasize ?*)  "Bold")
    ("/" (org-emphasize ?/)  "Italic")
    ("_" (org-emphasize ?_)  "Underlined")
    ("=" (org-emphasize ?=)  "Verbatim")
    ("~" (org-emphasize ?~)  "Code")
    ("+" (org-emphasize ?+)  "Strike-through"))))
#+END_SRC

** LaTeX

#+BEGIN_SRC emacs-lisp
(use-package auctex :ensure t)
(use-package cdlatex
  :ensure t)
#+END_SRC

Automatically render LaTeX fragments, toggle them when the cursor enters them.

#+BEGIN_SRC emacs-lisp
(use-package org-fragtog
  :ensure t
  :hook (org-mode . org-fragtog-mode))

(setq org-startup-with-latex-preview t)
#+END_SRC

** Nix

#+BEGIN_SRC emacs-lisp
(use-package nix-mode
  :ensure t
  :mode "\\.nix\\'"
  :hook (nix-mode . my:nix-mode-hook))

(defun my:nix-mode-hook ()
  (setq-local format-all-formatters '(("Nix" nixfmt))))
#+END_SRC

** Shell script
*** Sh, bash, zsh

Syntax checking and linting is provided by Shellcheck via flycheck.

#+BEGIN_SRC emacs-lisp
(add-hook 'sh-mode-hook 'flycheck-mode)
(setq bash-ts-mode-hook sh-mode-hook)
#+END_SRC

*** Fish

#+BEGIN_SRC emacs-lisp
(use-package fish-mode
  :ensure t
  :hook (fish-mode . flycheck-mode))
#+END_SRC

** Python

#+BEGIN_SRC emacs-lisp
(my:set-formatter python-mode "Python" black)
(setq python-ts-mode-hook python-mode-hook)
(add-hook 'python-ts-mode-hook 'lsp)
#+END_SRC

** Rust

#+BEGIN_SRC emacs-lisp
(use-package rustic
  :ensure t
  :hook (rustic-mode . company-mode)
  :custom
  (rustic-rustfmt-config-alist '(("edition" . "2021")))
  (rustic-format-display-method #'ignore)
  (rustic-format-trigger 'on-save)
  (rustic-format-on-save-method #'my:rust-format-on-save)
  (add-hook 'server-after-make-frame-hook #'catppuccin-reload)

  (lsp-inlay-hint-enable nil)
  (lsp-rust-analyzer-completion-add-call-argument-snippets nil)
  (lsp-rust-analyzer-completion-add-call-parenthesis nil)
  (lsp-rust-analyzer-display-lifetime-elision-hints-enable "skip_trivial")
  (lsp-rust-analyzer-display-chaining-hints t)
  (lsp-rust-analyzer-display-lifetime-elision-hints-use-parameter-names t)
  (lsp-rust-analyzer-display-closure-return-type-hints t)
  (lsp-rust-analyzer-display-parameter-hints t)
  (lsp-rust-analyzer-display-reborrow-hints t))
#+END_SRC

For some unknown reason, ~format-all-mode~ does not work with
rustic. Setting ~rustic-format-trigger~ enables formatting on save,
but it needs to check for ~format-all-mode~ in order to respect the
"Format on save" option in the [[*Toggle][Toggle hydra]].

#+BEGIN_SRC emacs-lisp
(defun my:rust-format-on-save ()
  "Format the file, respecting format-all-mode"
  (if format-all-mode
    (rustic-format-file)))
#+END_SRC

*** Hydra

#+BEGIN_SRC emacs-lisp
(major-mode-hydra-define rustic-mode
  (:exit t :idle 0.25 :quit-key "<escape>")
  ("Cargo"
   (("c" rustic-cargo-check                    "Check")
    ("m" rustic-cargo-add-missing-dependencies "Add missing dependencies")
    ("a" rustic-cargo-add                      "Add dependency")
    ("r" rustic-cargo-rm                       "Remove dependency"))))
#+END_SRC

** WGSL
#+BEGIN_SRC emacs-lisp
(use-package wgsl-mode
  :ensure t)
#+END_SRC
** Web

#+BEGIN_SRC emacs-lisp
(use-package web-mode
  :ensure t
  :hook (html-ts-mode . web-mode))

(add-hook 'web-mode-hook 'lsp)
(add-hook 'css-ts-mode-hook 'lsp)
(add-hook 'scss-mode-hook 'lsp)
(add-hook 'js-ts-mode-hook 'lsp)
(add-hook 'json-ts-mode-hook 'lsp)
(add-hook 'typescript-ts-mode-hook 'lsp)

(eval-after-load 'format-all '(progn
  (add-hook 'web-mode-hook (lambda ()
    (setq format-all-formatters
      '(("HTML" (prettier))))))
  (add-hook 'css-ts-mode-hook (lambda ()
    (setq format-all-formatters
      '(("CSS" (prettier))))))
  (add-hook 'scss-mode-hook (lambda ()
    (setq format-all-formatters
      '(("SCSS" (prettier))))))
  (add-hook 'js-ts-mode-hook (lambda ()
    (setq format-all-formatters
      '(("JavaScript" (prettier))))))
  (add-hook 'json-ts-mode-hook (lambda ()
    (setq format-all-formatters
      '(("JSON" (prettier))))))
  (add-hook 'typescript-mode-hook (lambda ()
    (setq format-all-formatters
      '(("TypeScript" (prettier))))))))
#+END_SRC

*** Tera / Jinja2

Use Jinja2 stuff for Tera. It's close enough.

#+BEGIN_SRC emacs-lisp
(use-package jinja2-mode :ensure t)

(eval-after-load 'format-all '(progn
  (define-format-all-formatter djlint
    (:executable "djlint")
    (:install)
    (:languages "HTML")
    (:features)
    (:format (format-all--buffer-easy executable "--reformat" "-")))
  (add-hook 'jinja2-mode-hook (lambda ()
    (setq format-all-formatters
      '(("HTML" (djlint))))))))
#+END_SRC
