#!/usr/bin/env bash

SCRIPT_DIR="$(dirname "$0")"
EMACS_BIN_DIR="@bin@"
LOG_FILE="/tmp/install-emacs.log"

GOOD=$(tput setaf 2)
BAD=$(tput setaf 1)
RESET=$(tput sgr0)


printdone () {
    printf '%s\n' " ${GOOD}Done${RESET}"
}

printerr () {
    printf '%s\n\n' " ${BAD}Error"
    cat $LOG_FILE
    printf '%s' "$RESET"
}

clean () {
    exec 3>&1 4>&2 1>>/dev/null 2>&1
    sudo rm "$@"
    exec 1>&3 2>&4 3>&- 4>&-
}

run() {
    exec 3>&1 4>&2 1>>"$LOG_FILE" 2>&1
    "$@"
    local exit_code=$?
    exec 1>&3 2>&4 3>&- 4>&-

    if [ $exit_code -ne 0 ]; then
	printerr
	exit 1
    fi
}


#
# Main
#

clean $LOG_FILE

printf '\n%s' "Copying .desktop files to /usr/share/applications..."
clean /usr/share/applications/fr33macs.*.desktop
run sudo cp "${SCRIPT_DIR}/fr33macs.emacs.desktop" /usr/share/applications
run sudo cp "${SCRIPT_DIR}/fr33macs.emacsclient.desktop" /usr/share/applications
printdone

printf "Setting up daemon service..."
run sudo cp "${SCRIPT_DIR}/fr33macs.emacs.service" /etc/systemd/user/emacs.service
run systemctl --user daemon-reload
run systemctl --user enable --now emacs
printdone

printf "Adding links to /usr/bin..."
clean /usr/bin/emacs
clean /usr/bin/emacsclient
run sudo ln -s "${EMACS_BIN_DIR}/emacs" /usr/bin/emacs
run sudo ln -s "${EMACS_BIN_DIR}/emacsclient" /usr/bin/emacsclient
printdone

printf '\n%s\n\n' "${GOOD}Successfully installed.${RESET}"

# Ignore this unused replacement: @icon@
